---
### Clean remove of all zabbix repo, pkg,config and logs on zabbix-agent host.
### 

- debug:
    msg: "Clean remove of all zabbix repo, pkg,config and logs on  server {{ ansible_hostname }} "

- name: remove zabbix repo and packages.
  yum:
    name:  zabbix-agent
    state: absent

- name: remove zabbix repo and packages.
  yum:
    name:  zabbix-release
    state: absent

- name: Delete /etc/zabbix dir
  file:
    state: absent
    path:  /etc/zabbix

- name: Delete zabbix log files.
  file:
    state: absent
    path:  /var/log/zabbix

